#!/usr/bin/env bash
set -euo pipefail

rm -rf ghcide

niv="$(nix-build nix -A devTools.niv)/bin/niv"
"$niv" update ghcide
# stack-to-nix will select a newer snapshot, requiring new stackage.nix
"$niv" update haskell.nix

rev=$(nix eval --raw "(builtins.fromJSON (builtins.readFile ./nix/sources.json)).ghcide.rev")
git clone https://github.com/digital-asset/ghcide
pushd ghcide
  git checkout $rev
  $(nix-build ../nix -A haskellnix.nix-tools --no-out-link)/bin/stack-to-nix -o ../nix/stack
popd
rm -rf ghcide
